### ISSUE TITLE
Popular Latin abbreviations

### ISSUE THREAD

**Issue by aserebrenik** [AlexDings/TUe_LaTeX#1]
Consider adding popular Latin abbreviations:

```
\usepackage{xspace}
\newcommand{\etal}{et al.\xspace}
\newcommand{\ie}{i.e.,\xspace}
\newcommand{\eg}{e.g.,\xspace}
```

**Comment by AlexDings** [comment]
Abbreviations are in there.
Swallowing of spaces is solved by adding a mandatory / after a definition.
For example: \ie --> \ie/
